version: '3.8'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'myvetshop_db'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: ''
      MYSQL_ROOT_PASSWORD: ''
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 baseteran.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DJANGO_SECRET_KEY='django-insecure-#v2=wr9b)@s@9ragdm1#cmyxd#+&^08(#3e=j3^gg(l562qnf^'
      - DB_NAME='myvetshop_db'
      - DB_USER='root'
      - DB_PASSWORD=''
      - DB_HOST='db'  
      - DB_PORT=3306

volumes:
  mysql_data:

