version: '3.8'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=myvetshop_db
      - POSTGRES_USER=lucas
      - POSTGRES_PASSWORD=T3csup3637
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tecsup

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 baseteran.wsgi:application
    volumes:
      - .:/app
    ports:
      - "5432:5432"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DJANGO_SECRET_KEY=django-insecure-#v2=wr9b)@s@9ragdm1#cmyxd#+&^08(#3e=j3^gg(l562qnf^
      - DB_NAME=myvetshop_db
      - DB_USER=lucas
      - DB_PASSWORD=T3csup3637
      - DB_PORT=5432
    networks:
      - tecsup

volumes:
  mysql_data: